name: Deploy Web en VPS

on:
  push:
    branches:
      - main # Se ejecuta cuando hay cambios en main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Docker
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mi-web:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-web:latest

      - name: Conectar con VPS y actualizar contenedor
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mi-web:latest
            docker stop mi_web || true
            docker rm mi_web || true
            docker run -d --name mi_web -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/mi-web:latest
          EOF
